import type { StructuredState } from './modelApi';
export type Prospect = { structured?: StructuredState; publicEvidenceMode?: 'demo' | 'verified'; id: number; name: string; initials: string; owner: string; country: string; flag: string; sector: string; employees: number; revenue: string; score: number | null; type: string; signal: string; second: string; confidence: 'High' | 'Moderate' | 'Low'; sources: number; color: string; angle: string };
export const prospects: Prospect[] = [
 {id:1,name:'Schneider Präzisionstechnik',initials:'SP',owner:'Thomas Schneider',country:'Germany',flag:'🇩🇪',sector:'Manufacturing',employees:120,revenue:'€24.6m',score:null,type:'Succession / partial exit',signal:'External CEO appointed',second:'Founder moves to advisory role',confidence:'Low',sources:0,color:'sage',angle:'A next chapter, on your terms'},
 {id:2,name:'Nordvik Industrial',initials:'NI',owner:'Lars Eriksson',country:'Sweden',flag:'🇸🇪',sector:'Manufacturing',employees:165,revenue:'€31.2m',score:null,type:'Strategic partner',signal:'International expansion planned',second:'Ownership concentrated with founder',confidence:'Low',sources:0,color:'blue',angle:'The right partner for your next market'},
 {id:3,name:'Kraftwerk Solutions',initials:'KS',owner:'Michael Weber',country:'Germany',flag:'🇩🇪',sector:'Industrial services',employees:85,revenue:'€16.8m',score:null,type:'Growth capital',signal:'New production facility announced',second:'Expansion into two new markets',confidence:'Low',sources:0,color:'sand',angle:'Capital to support your next phase'},
 {id:4,name:'Aalto Health Technologies',initials:'AH',owner:'Sanna Laine',country:'Finland',flag:'🇫🇮',sector:'Healthcare',employees:64,revenue:'€12.4m',score:null,type:'Minority investment',signal:'New product investment cycle',second:'Founder retains majority ownership',confidence:'Low',sources:0,color:'rose',angle:'Growth without giving up control'},
 {id:5,name:'Bergmann Components',initials:'BC',owner:'Andreas Bergmann',country:'Germany',flag:'🇩🇪',sector:'Manufacturing',employees:200,revenue:'€42.1m',score:null,type:'Strategic partner',signal:'Management team strengthened',second:'New international distribution',confidence:'Low',sources:0,color:'lilac',angle:'Building on your international momentum'},
 {id:6,name:'Fischer Medizintechnik',initials:'FM',owner:'Claudia Fischer',country:'Germany',flag:'🇩🇪',sector:'Healthcare',employees:90,revenue:'€18.3m',score:null,type:'Partial sale',signal:'Founder exploring advisory roles',second:'Operational handover unconfirmed',confidence:'Low',sources:0,color:'blue',angle:'Exploring flexibility for the future'},
 {id:7,name:'Lindholm Packaging',initials:'LP',owner:'Henrik Lindholm',country:'Denmark',flag:'🇩🇰',sector:'Packaging',employees:110,revenue:'€21.7m',score:null,type:'Full exit',signal:'Ownership review reported',second:'Transaction scope unconfirmed',confidence:'Low',sources:0,color:'sage',angle:'A confidential conversation about succession'},
 {id:8,name:'Hoffmann Elektronik',initials:'HE',owner:'Stefan Hoffmann',country:'Germany',flag:'🇩🇪',sector:'Electronics',employees:45,revenue:'—',score:null,type:'Not established',signal:'No corroborated transition signals',second:'More research needed',confidence:'Low',sources:0,color:'gray',angle:'Hold outreach until evidence improves'},
];
export const nordicCountries = ['Sweden','Finland','Denmark'];
