export type Prospect = { id: number; name: string; initials: string; owner: string; country: string; flag: string; sector: string; employees: number; revenue: string; score: number | null; type: string; signal: string; second: string; confidence: 'High' | 'Moderate' | 'Low'; sources: number; color: string; angle: string };
export const prospects: Prospect[] = [
 {id:1,name:'Schneider Präzisionstechnik',initials:'SP',owner:'Thomas Schneider',country:'Germany',flag:'🇩🇪',sector:'Manufacturing',employees:120,revenue:'€24.6m',score:87,type:'Succession / partial exit',signal:'External CEO appointed',second:'Founder moves to advisory role',confidence:'High',sources:6,color:'sage',angle:'A next chapter, on your terms'},
 {id:2,name:'Nordvik Industrial',initials:'NI',owner:'Lars Eriksson',country:'Sweden',flag:'🇸🇪',sector:'Manufacturing',employees:165,revenue:'€31.2m',score:84,type:'Strategic partner',signal:'International expansion planned',second:'Ownership concentrated with founder',confidence:'High',sources:8,color:'blue',angle:'The right partner for your next market'},
 {id:3,name:'Kraftwerk Solutions',initials:'KS',owner:'Michael Weber',country:'Germany',flag:'🇩🇪',sector:'Industrial services',employees:85,revenue:'€16.8m',score:81,type:'Growth capital',signal:'New production facility announced',second:'Expansion into two new markets',confidence:'High',sources:5,color:'sand',angle:'Capital to support your next phase'},
 {id:4,name:'Aalto Health Technologies',initials:'AH',owner:'Sanna Laine',country:'Finland',flag:'🇫🇮',sector:'Healthcare',employees:64,revenue:'€12.4m',score:78,type:'Minority investment',signal:'New product investment cycle',second:'Founder retains majority ownership',confidence:'High',sources:7,color:'rose',angle:'Growth without giving up control'},
 {id:5,name:'Bergmann Components',initials:'BC',owner:'Andreas Bergmann',country:'Germany',flag:'🇩🇪',sector:'Manufacturing',employees:200,revenue:'€42.1m',score:73,type:'Strategic partner',signal:'Management team strengthened',second:'New international distribution',confidence:'Moderate',sources:4,color:'lilac',angle:'Building on your international momentum'},
 {id:6,name:'Fischer Medizintechnik',initials:'FM',owner:'Claudia Fischer',country:'Germany',flag:'🇩🇪',sector:'Healthcare',employees:90,revenue:'€18.3m',score:62,type:'Partial sale',signal:'Founder exploring advisory roles',second:'Operational handover unconfirmed',confidence:'Moderate',sources:3,color:'blue',angle:'Exploring flexibility for the future'},
 {id:7,name:'Lindholm Packaging',initials:'LP',owner:'Henrik Lindholm',country:'Denmark',flag:'🇩🇰',sector:'Packaging',employees:110,revenue:'€21.7m',score:58,type:'Full exit',signal:'Ownership review reported',second:'Transaction scope unconfirmed',confidence:'Moderate',sources:3,color:'sage',angle:'A confidential conversation about succession'},
 {id:8,name:'Hoffmann Elektronik',initials:'HE',owner:'Stefan Hoffmann',country:'Germany',flag:'🇩🇪',sector:'Electronics',employees:45,revenue:'—',score:null,type:'Not established',signal:'No corroborated transition signals',second:'More research needed',confidence:'Low',sources:1,color:'gray',angle:'Hold outreach until evidence improves'},
];
export const nordicCountries = ['Sweden','Finland','Denmark'];
export function messageFor(p: Prospect, tone='Considered') { return `Dear ${p.owner.split(' ')[0]},\n\n${p.id === 1 ? 'I noticed the recent leadership transition at Schneider Präzisionstechnik. Building a business of this calibre, and putting the right team in place for its next chapter, is a significant achievement.' : `I noticed ${p.name}’s recent developments, particularly ${p.signal.toLowerCase()}. It looks like an important chapter for the business.`}\n\nAt Mergero, we work with owners ${p.type.includes('Succession') || p.type === 'Partial sale' ? 'considering their next chapter — whether that means taking some capital off the table, finding a long-term partner, or remaining involved in a different capacity.' : `exploring ${p.type.toLowerCase()}, with an emphasis on preserving what makes their business successful.`}\n\n${tone === 'Concise' ? 'Would you be open to a brief, confidential conversation?' : 'If exploring options is relevant, now or further down the line, I would welcome a brief, confidential conversation. There is no assumption that you are looking to sell.'}\n\nBest regards,\nAlexander Keller\nMergero`; }
