import { ArrowRight, ShieldCheck } from 'lucide-react';
import { StructuredModel } from './StructuredModel';
import type { Prospect } from './data';
import { investigate, type Evidence } from './research';

export function EvidenceRecord({item}:{item:Evidence}) {
 return <article className={`claim-record ${item.status==='Conflicting'?'conflict':''}`} id={item.id}>
  <header><span className={`evidence-status status-${item.status.split(' ')[0].toLowerCase()}`}>{item.status}</span><strong className={item.impact<0?'negative':''}>{item.impact>0?'+':''}{Number(item.impact.toFixed(1))} priority points*</strong></header>
  <h4>{item.signal}</h4><dl><div><dt>Interpretation</dt><dd>{item.interpretation}</dd></div><div><dt>Evidence strength</dt><dd>{item.strength} · {item.sources.some(s=>s.independent)&&item.status==='Verified'?'Independently confirmed':item.status==='Conflicting'?'Counter-evidence found; claim unresolved':'Independent confirmation missing'}</dd></div></dl>
  <div className="claim-provenance">{item.sources.map(s=><span key={s.id}>{s.publisher} · <time>{s.date}</time>{s.independent?' · Independent source':''}</span>)}</div>
  <details><summary>{item.sources.length} source records · inspect excerpts</summary>{item.sources.map(s=><div className="source-excerpt" key={s.id}><strong>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>:s.title}</strong><span>{s.publisher} · <time>{s.date}</time></span><p>{s.excerpt}</p><small>{s.independent?'Independent of company disclosure':'Company / registry origin'} · {s.mode==='live'?'Live public source':'Mock source record'}{s.stance?' / '+s.stance:''}{s.note?' / '+s.note:''}</small></div>)}</details>
 </article>
}

export function InvestigationBody({p,tab,setTab,message,copy,onUpdate}:{onUpdate:(p:Prospect)=>void;p:Prospect;tab:string;setTab:(s:string)=>void;message:string;copy:(s:string)=>void}) {
 const r=investigate(p);const live=p.publicResearch?.status==='live'?p.publicResearch.report:null;
 return <><div className="investigation-model"><ShieldCheck size={15}/><span>{r.model}</span><span>{r.combined?.mode} · {live?'live public evidence':'demo public sources'}</span></div>
 <div className="demo-evidence">{live?`Live public evidence / ${live.cache_hit?'cached':'new'} / researched ${live.researched_at.slice(0,10)}. ${live.verification_method}. Advisor review remains required.`:p.publicResearch?.status==='unavailable'?`Public research unavailable / demo fallback: ${p.publicResearch.error}`:'Illustrative evidence records. No live sources connected to this example.'}</div>
 {live&&<div className="research-gaps"><strong>Missing information</strong><p>{live.data_gaps.join('; ')||'No checklist gaps reported. This does not establish owner intent.'}</p>{live.warnings.map(w=><p key={w}>{w}</p>)}</div>}
 {tab==='Overview'?<>
  <div className="verdict"><div><span className="section-label">EXPLAINED RESEARCH PRIORITY</span><h3>{r.score??'—'}{r.score!==null&&<small>/100</small>}</h3></div><div><strong>{r.contact?'Worth a considered conversation':r.draftAllowed?'Illustrative conversation · review required':'Do not contact yet'}</strong><p>{r.confidence} confidence · {r.evidence.filter(e=>e.status==='Verified').length} verified claims</p><button className="text-button" onClick={()=>setTab('Why this score?')}>Why this score? <ArrowRight size={13}/></button></div></div>
  <StructuredModel p={p} onUpdate={onUpdate}/>
  <div className="combined-assessment"><div className="eyebrow">FINAL COMBINED ASSESSMENT</div><p>{r.combined?.explanation}</p><small>Structured weight: up to {Math.round((r.combined?.nominalStructuredWeight??0)*100)}% in this region × {(100*(r.combined?.coverage??0)).toFixed(0)}% observed-field coverage. Missing data reduces confidence. Contradictions are subtracted after blending and cannot be diluted by the model.</small></div>
  <p className="intent-note">A signal does not automatically mean willingness to sell. This is a research-priority score, not a probability of sale.</p>
  <div className="investigation-section"><span className="eyebrow">01 / FIND & CROSS-CHECK</span><h3>Public-signal evidence & contradictions</h3>{r.evidence.filter(e=>live||e.id!=='e3').map(e=><EvidenceRecord key={e.id} item={e}/>)}<small className="weight-note">*Signal points feed the category ledger. Evidence quality and independent corroboration add separate, explicit contributions.</small></div>
  <div className="investigation-section score-summary"><span className="eyebrow">02 / WEIGH THE EVIDENCE</span><h3>Why this priority?</h3><p>{r.score===null?'Insufficient evidence. No score assigned.':r.combined?.explanation}</p><button className="text-button" onClick={()=>setTab('Why this score?')}>Inspect the scoring ledger <ArrowRight size={13}/></button></div>
  <div className="investigation-section"><span className="eyebrow">03 / CHOOSE THE CONVERSATION</span><h3>{r.transaction}</h3><p>{r.transactionReason}</p><div className={`contact-recommendation ${r.contact?'':'hold'}`}><strong>{r.contact?'Recommended next step':'Do not contact yet'}</strong><p>{r.nextStep}</p></div>{r.draftAllowed&&<button className="text-button" onClick={()=>setTab('Outreach')}>Read the personalized introduction <ArrowRight size={13}/></button>}</div>
 </>:tab==='Signals'?<><h3 className="investigation-title">Signals / evidence</h3><p className="muted-copy">{r.regionalReason}</p>{r.evidence.map(e=><EvidenceRecord key={e.id} item={e}/>)}<p className="weight-note">Signal points feed the category ledger; quality and corroboration are assessed separately. {live?'Open source links to review the automated cross-check. Unknown dates and shared origins cannot establish independent confirmation.':'Source records are fictional and intentionally have no live citation links.'}</p></>:tab==='Why this score?'?<><h3 className="investigation-title">Why this score?</h3><p className="muted-copy">{r.regionalReason}</p><StructuredModel p={p} onUpdate={onUpdate}/><p className="intent-note">Public-signal ledger only. Structured ownership and financial features are scored by Java and excluded here to avoid double-counting. Positive caps total 100; contradiction penalties apply after regional blending. This is an uncalibrated prioritization policy.</p><div className="score-ledger">{r.factors.map(f=><div className="score-factor" key={f.label}><div><h4>{f.label}</h4><p>{f.reason}</p><button className="text-button" onClick={()=>setTab('Signals')}>Evidence {f.evidenceIds.join(', ')} →</button></div><strong className={f.points<0?'negative':''}>{f.points>0?'+':''}{Number(f.points.toFixed(1))}<small>{f.maximum?`of ${f.maximum.toFixed(1)} max`:'penalty'}</small></strong></div>)}</div><p className="combined-formula">{r.combined?.explanation}</p><div className="score-total"><span>{r.score===null?'Insufficient evidence — no score assigned':'Total research priority'}</span><strong>{r.score??'—'}{r.score!==null&&' / 100'}</strong></div><p className="muted-copy">Contact gate: at least 70 combined points, high confidence, independently corroborated principal claims, and validated non-demo evidence. Synthetic models, {live?'live public evidence':'demo public sources'} and unavailable APIs cannot authorize real outreach. Qualified demo cases can still generate an explicitly illustrative draft.</p></>:<><h3 className="investigation-title">The conversation we would start</h3><p className="muted-copy">{r.transactionReason}</p>{r.draftAllowed?<><div className="demo-evidence">{r.contact?'Advisor review required':'Review-only draft - verify source interpretation and model validity before use.'}</div><div className="outreach-grounding"><strong>Grounded in verified evidence</strong><p>{r.outreachFact}</p><small>Counter-evidence constrains the framing; no claim of sale intent.</small></div><div className="message-card"><span>REVIEWABLE EMAIL DRAFT</span><h4>Subject: {p.name}’s next chapter</h4><p>{message}</p></div><button className="secondary full-width" onClick={()=>copy(message)}>Copy message</button></>:<div className="contact-recommendation hold"><strong>Do not contact yet</strong><p>{r.nextStep}</p><p>No outreach is generated from unverified claims.</p></div>}</>}
 </>;
}

export {DiscoverResearch} from './DiscoverResearch';
