import { useEffect, useState } from 'react';
import { ArrowRight, Check, Search, ShieldCheck } from 'lucide-react';
import type { Prospect } from './data';
import { assessedProspect, investigate, type Evidence } from './research';

export function EvidenceRecord({item}:{item:Evidence}) {
 return <article className={`claim-record ${item.status==='Conflicting'?'conflict':''}`} id={item.id}>
  <header><span className={`evidence-status status-${item.status.split(' ')[0].toLowerCase()}`}>{item.status}</span><strong className={item.impact<0?'negative':''}>{item.impact>0?'+':''}{item.impact} priority points*</strong></header>
  <h4>{item.signal}</h4><dl><div><dt>Interpretation</dt><dd>{item.interpretation}</dd></div><div><dt>Evidence strength</dt><dd>{item.strength} · {item.sources.some(s=>s.independent)&&item.status==='Verified'?'Independently confirmed':item.status==='Conflicting'?'Counter-evidence found; claim unresolved':'Independent confirmation missing'}</dd></div></dl>
  <div className="claim-provenance">{item.sources.map(s=><span key={s.id}>{s.publisher} · <time>{s.date}</time>{s.independent?' · Independent source':''}</span>)}</div>
  <details><summary>{item.sources.length} source records · inspect excerpts</summary>{item.sources.map(s=><div className="source-excerpt" key={s.id}><strong>{s.title}</strong><span>{s.publisher} · <time>{s.date}</time></span><p>{s.excerpt}</p><small>{s.independent?'Independent of company disclosure':'Company / registry origin'} · Mock source record</small></div>)}</details>
 </article>
}

export function InvestigationBody({p,tab,setTab,message,copy}:{p:Prospect;tab:string;setTab:(s:string)=>void;message:string;copy:(s:string)=>void}) {
 const r=investigate(p);const positive=r.factors.filter(f=>f.points>0).reduce((a,f)=>a+f.points,0);const penalty=r.factors.filter(f=>f.points<0).reduce((a,f)=>a+f.points,0);
 return <><div className="investigation-model"><ShieldCheck size={15}/><span>{r.model}</span><span>Mock investigation</span></div>
 {tab==='Overview'?<>
  <div className="verdict"><div><span className="section-label">EXPLAINED RESEARCH PRIORITY</span><h3>{r.score??'—'}{r.score!==null&&<small>/100</small>}</h3></div><div><strong>{r.contact?'Worth a considered conversation':'Do not contact yet'}</strong><p>{r.confidence} confidence · {r.evidence.filter(e=>e.status==='Verified').length} verified claims</p><button className="text-button" onClick={()=>setTab('Why this score?')}>Why this score? <ArrowRight size={13}/></button></div></div>
  <p className="intent-note">A signal does not automatically mean willingness to sell. This is a research-priority score, not a probability of sale.</p>
  <div className="investigation-section"><span className="eyebrow">01 / FIND & CROSS-CHECK</span><h3>What the evidence tells us</h3>{r.evidence.filter(e=>e.id!=='e3').map(e=><EvidenceRecord key={e.id} item={e}/>)}<small className="weight-note">*Signal points feed the category ledger. Evidence quality and independent corroboration add separate, explicit contributions.</small></div>
  <div className="investigation-section score-summary"><span className="eyebrow">02 / WEIGH THE EVIDENCE</span><h3>Why this priority?</h3><p>{r.score===null?'Insufficient evidence. No score assigned.':`${positive} positive category points ${penalty<0?`− ${Math.abs(penalty)} for contradictory evidence`:'+ 0 uncertainty points'} = ${r.score} priority points.`}</p><button className="text-button" onClick={()=>setTab('Why this score?')}>Inspect all eight contributions <ArrowRight size={13}/></button></div>
  <div className="investigation-section"><span className="eyebrow">03 / CHOOSE THE CONVERSATION</span><h3>{r.transaction}</h3><p>{r.transactionReason}</p><div className={`contact-recommendation ${r.contact?'':'hold'}`}><strong>{r.contact?'Recommended next step':'Do not contact yet'}</strong><p>{r.nextStep}</p></div>{r.contact&&<button className="text-button" onClick={()=>setTab('Outreach')}>Read the personalized introduction <ArrowRight size={13}/></button>}</div>
 </>:tab==='Signals'?<><h3 className="investigation-title">Signals / evidence</h3><p className="muted-copy">{r.regionalReason}</p><div className="demo-evidence">Illustrative evidence records. No live sources connected.</div>{r.evidence.map(e=><EvidenceRecord key={e.id} item={e}/>)}<p className="weight-note">Signal points feed the category ledger; quality and corroboration are assessed separately. Source records are fictional and intentionally have no live citation links.</p></>:tab==='Why this score?'?<><h3 className="investigation-title">Why this score?</h3><p className="muted-copy">{r.regionalReason}</p><p className="intent-note">Starting score: 0. Positive category caps total 100. Contradictions subtract points. This transparent demo rubric is not a statistically calibrated prediction.</p><div className="score-ledger">{r.factors.map(f=><div className="score-factor" key={f.label}><div><h4>{f.label}</h4><p>{f.reason}</p><button className="text-button" onClick={()=>setTab('Signals')}>Evidence {f.evidenceIds.join(', ')} →</button></div><strong className={f.points<0?'negative':''}>{f.points>0?'+':''}{f.points}<small>{f.maximum?`of ${f.maximum} max`:'penalty'}</small></strong></div>)}</div><div className="score-total"><span>{r.score===null?'Insufficient evidence — no score assigned':'Total research priority'}</span><strong>{r.score??'—'}{r.score!==null&&' / 100'}</strong></div><p className="muted-copy">Contact gate: at least 70 points, high confidence, and independent confirmation of the principal claims. Weak evidence blocks outreach even when there is a plausible transaction hypothesis.</p></>:<><h3 className="investigation-title">The conversation we would start</h3><p className="muted-copy">{r.transactionReason}</p>{r.contact?<><div className="outreach-grounding"><strong>Grounded in verified evidence</strong><p>{r.outreachFact}</p><small>Counter-evidence constrains the framing; no claim of sale intent.</small></div><div className="message-card"><span>REVIEWABLE EMAIL DRAFT</span><h4>Subject: {p.name}’s next chapter</h4><p>{message}</p></div><button className="secondary full-width" onClick={()=>copy(message)}>Copy message</button></>:<div className="contact-recommendation hold"><strong>Do not contact yet</strong><p>{r.nextStep}</p><p>No outreach is generated from unverified claims.</p></div>}</>}
 </>;
}

export function DiscoverResearch({prospects,onComplete}:{prospects:Prospect[];onComplete:(p:Prospect)=>void}) {
 const [input,setInput]=useState('');const [country,setCountry]=useState('Germany');const [target,setTarget]=useState<Prospect|null>(null);const [stage,setStage]=useState(-1);
 useEffect(()=>{if(stage<0||stage>=4)return;const timer=window.setTimeout(()=>setStage(s=>s+1),850);return()=>window.clearTimeout(timer)},[stage]);
 const r=target?investigate(target):null;
 const sources=r?Array.from(new Map(r.evidence.flatMap(e=>e.sources).map(s=>[s.id,s])).values()):[];
 function start(){const query=input.trim();if(!query)return;const existing=prospects.find(p=>p.name.toLowerCase()===query.toLowerCase()||p.name.toLowerCase().includes(query.toLowerCase()));const p=existing||assessedProspect({id:Date.now(),name:query,initials:query.slice(0,2).toUpperCase(),owner:'Not established',country,flag:'',sector:'Not established',employees:0,revenue:'—',score:null,type:'Not established',signal:'No corroborated transition signals',second:'More research needed',confidence:'Low',sources:0,color:'gray',angle:'Hold outreach until evidence improves'});setTarget(p);setStage(0)}
 return <><div className="eyebrow">FROM PUBLIC SIGNAL TO PRIVATE CONVERSATION</div><h2 id="modal-title">Investigate a company.</h2><p className="muted-copy">A simulated research run with inspectable evidence. Example companies have prepared records; unknown companies return insufficient evidence.</p>{stage<0?<><label className="form-field">Company name<input autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')start()}} placeholder="Enter a company to investigate"/></label><label className="form-field">Market for new company<select value={country} onChange={e=>setCountry(e.target.value)}>{['Germany','Sweden','Finland','Denmark','France','Netherlands'].map(c=><option key={c}>{c}</option>)}</select></label><div className="example-choices"><span>Or choose a prepared investigation</span>{[1,2,8].map(id=>{const p=prospects.find(x=>x.id===id)!;return <button key={id} className={input===p.name?'selected':''} onClick={()=>setInput(p.name)}><span>{p.name}</span><small>{id===1?'Verified handover + contradictory intent':id===2?'Nordic registry + expansion context':'Weak evidence · do not contact'}</small></button>})}</div><button className="primary full-width" disabled={!input.trim()} onClick={start}><Search size={15}/> Research company</button></>:<><div className="research-target"><strong>{target?.name}</strong><span>{r?.model}</span></div><ol className="research-stages" aria-live="polite">{['Researching public sources','Extracting relevant signals','Cross-checking independent evidence','Weighing contradictions & explaining priority','Investigation complete'].map((s,i)=><li key={s} className={stage===i?'current':stage>i?'complete':''}><span>{stage>i?<Check size={12}/>:i+1}</span>{s}</li>)}</ol><div className="research-results" aria-live="polite"><h3>{stage<2?'Sources being checked':'Evidence trail'}</h3>{sources.map(s=><div className="research-source" key={s.id}><span>{stage>0?<Check size={13}/>:<Search size={13}/>}</span><div><strong>{s.publisher}</strong><small>{s.title} · {s.date}</small></div></div>)}{stage>=2&&<div className="research-findings">{r?.evidence.map(e=><p key={e.id}><span className={`evidence-status status-${e.status.split(' ')[0].toLowerCase()}`}>{e.status}</span>{e.signal}</p>)}</div>}{stage===4&&<div className="research-outcome"><strong>{r?.contact?`${r.score}/100 · Considered outreach`:'Do not contact yet'}</strong><p>{r?.contact?r.transactionReason:r?.nextStep}</p></div>}</div>{stage===4?<button className="primary full-width" onClick={()=>target&&onComplete(target)}>Open investigation <ArrowRight size={15}/></button>:<p className="research-wait" role="status">Mock research in progress…</p>}</>}</>;
}
