import { useEffect, useState } from 'react';
import type { Prospect } from './data';
import { companyInput, scoreCompany, structuredFields, type CompanyInput } from './modelApi';

export function StructuredInputs({value,onChange}:{value:CompanyInput;onChange:(v:CompanyInput)=>void}) {
 return <div className="structured-inputs"><label>Observation year<input type="number" min="1900" max="2200" required value={value.year} onChange={e=>onChange({...value,year:Number(e.target.value)})}/></label>{structuredFields.map(([key,label])=><label key={key}>{label}{key==='familyOwned'?<select value={value.familyOwned==null?'':String(value.familyOwned)} onChange={e=>onChange({...value,familyOwned:e.target.value===''?null:e.target.value==='true'})}><option value="">Unknown</option><option value="true">Yes</option><option value="false">No</option></select>:<input type="number" step="any" placeholder="Unknown" value={value[key]??''} onChange={e=>onChange({...value,[key]:e.target.value===''?null:Number(e.target.value)})}/>}</label>)}</div>;
}

export function StructuredModel({p,onUpdate}:{p:Prospect;onUpdate:(p:Prospect)=>void}) {
 const [input,setInput]=useState(()=>companyInput(p));const [busy,setBusy]=useState(false);
 useEffect(()=>{setInput(companyInput(p));setBusy(false)},[p.id,p.structured]);
 const state=p.structured;const result=state?.status==='ready'?state.result:null;
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const structured=await scoreCompany(input,undefined,'user-supplied');onUpdate({...p,structured});setBusy(false)}
 return <section className="structured-model"><div className="eyebrow">STRUCTURED MODEL EVIDENCE</div><h3>{result?result.metadata.modelUsed:'Java company model'}</h3><p className="model-status">{!state?'Model not yet loaded':state.status==='unavailable'?`API unavailable · explicit demo fallback. ${state.error}`:result?.status==='insufficient_data'?'Insufficient structured data — no model score assigned':`${result?.metadata.syntheticTraining?'Live Java computation · synthetic training':'Live Java model'} · ${result?.confidence} input coverage confidence`}</p>
 {result&&<><div className="model-readout"><div><span>Historical acquisition propensity</span><strong>{result.probability===null?'—':(result.probability*100).toFixed(2)+'%'}</strong></div><div><span>Reference-cohort percentile</span><strong>{result.percentile===null?'—':result.percentile.toFixed(1)}</strong></div><div><span>Observed fields</span><strong>{result.suppliedFields.length} / {structuredFields.length}</strong></div></div><p className="intent-note">Predicts historical sale/acquisition patterns from structured features. This is not a probability that the owner wants to sell.</p><p className="model-provenance">Training: {result.metadata.trainingSource} · through {result.metadata.trainedThroughYear} · {result.metadata.trainingRows.toLocaleString()} rows. Inputs: {state?.inputProvenance}. {p.publicResearch?.status==='live'?'Public evidence: live research.':'Public evidence: demo fixtures.'}</p>{p.publicResearch?.status==='live'&&<details><summary>Structured fact provenance</summary>{p.publicResearch.report.structured_facts.map((f,i)=><p className="model-provenance" key={f.field+i}>{f.field}: {String(f.value)} / as of {f.as_of||'unknown'} / {f.sources.map(url=><a key={url} href={url} target="_blank" rel="noreferrer">{new URL(url).hostname} </a>)}</p>)}</details>}<details><summary>Inspect model contributions & missing fields</summary><p className="muted-copy">Missing: {result.missingFields.join(', ')||'none'}. Imputation is a mathematical fallback, not observed evidence. Contributions are additive log-odds, not priority points.</p>{result.contributions.map(c=><div className="model-contribution" key={c.feature}><span>{c.feature}<small>{c.imputed?'Missing · internally imputed':`Observed feature: ${c.observedValue}`}</small></span><strong>{c.logOdds>=0?'+':''}{c.logOdds.toFixed(3)}</strong></div>)}<p className="muted-copy">Baseline log-odds: {result.baselineLogOdds?.toFixed(3)??'—'}. Baseline + all contributions = logit(model probability). {result.metadata.explanationMethod}.</p>{result.warnings.map(w=><p className="model-warning" key={w}>{w}</p>)}</details></>}
 <details className="structured-editor"><summary>Review / edit structured inputs{state?.status==='unavailable'?' and retry':''}</summary><p className="muted-copy">Use facts known before the observation year. Blank means unknown. Existing company values are labeled demo fixtures; editing does not independently verify them.</p><form onSubmit={submit}><StructuredInputs value={input} onChange={setInput}/><button className="secondary" disabled={busy}>{busy?'Scoring…':'Run structured model'}</button></form></details>
 </section>;
}
